### ISSUE TITLE
Detection of frozen strings doesn't work for Ruby 3.4 chilled strings

### ISSUE THREAD

**Issue by jeremyevans** [jlong/radius#25]
The code at https://github.com/jlong/radius/blob/master/lib/radius/utility.rb#L38 doesn't work correctly for Ruby 3.4 chilled strings. You need to switch from `res.frozen? ? res.dup : res` to `+res`, similar to what I did in Erubi (jeremyevans/erubi@6aa6f52, and you may want a similar fallback approach). This was found by the tilt specs.

This doesn't look maintained (no commits for 5 years), so absent a fix, I plan to remove radius support from tilt.

**Comment by saturnflyer** [comment]
@jeremyevans I'll release a new version soon.

**Comment by jeremyevans** [comment]
Awesome, thanks for your work on this!

**Comment by saturnflyer** [comment]
@jeremyevans updated and released 0.8.0
Please let us know if there are any other issues.

**Comment by jeremyevans** [comment]
Thank you for your quick work on this. I removed the warning filter in tilt: https://github.com/jeremyevans/tilt/commit/a0075b95d125f701ee2980a9a4054785b56ba04c
